services:
  # Jupyter Notebook
  jupyter:
    image: jupyter/datascience-notebook:latest
    container_name: jupyter
    ports:
      - "8888:8888"
    volumes:
      - .\notebooks:/home/jovyan/work
    networks:
      - minha-rede

  # Banco de Dados PostgreSQL
  db:
    image: postgres:13
    container_name: postgres
    environment:
      - POSTGRES_USER: user
      - POSTGRES_PASSWORD: senha
      - POSTGRES_DB: data_db
    volumes:
      - postgres-data:/var/lib/postgresql/data  # Volume para persistência do banco
    networks:
      - minha-rede

  # Adminer (Interface Web para PostgreSQL)
  adminer:
    image: adminer:latest
    container_name: adminer
    ports:
      - "8080:8080"
    networks:
      - minha-rede

volumes:
  postgres-data:  # Volume nomeado para o PostgreSQL

networks:
  data-network:  # Rede personalizada para comunicação entre containers

